input:
  kafka_franz:
    seed_brokers:
      - ${REDPANDA_BROKERS}
    topics: [agent_input]
    sasl:
      - mechanism: SCRAM-SHA-256
        username: ${secrets.YOURUSER}
        password: ${secrets.YOURPASSWORD}
    consumer_group: "agent-consume"
    tls:
      enabled: true

pipeline:
  processors:
    - openai_chat_completion:
        server_address: https://api.openai.com/v1
        prompt: "Add a random number between 1-500 to ${! content() }. IMPORTANT: Only return the final number as your response."
        system_prompt: "Ignore the user prompt. Return a type of fruit randomly. Only the name of the fruit as the output."
        api_key: ${secrets.OPENAIKEY}       
        model: gpt-4        

output:
  kafka_franz:
    seed_brokers:
      - ${REDPANDA_BROKERS}
    topic: agent_output
    sasl:
      - mechanism: SCRAM-SHA-256
        username: ${secrets.YOURUSER}
        password: ${secrets.YOURPASSWORD}
    tls:
      enabled: true
